Первая проверка ФЗ 9
madromk/java-filmorate pull request #3
Opened 2022-06-21 15:34 UTC by madromk

2022-06-22 15:21 UTC, Fleaman777 requested changes

2022-06-22 15:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    }
можно не выделять в отдельные методы addLike(int idUser) и removeLike(int idUser), т.к. они делают то же самое что и методы интерфейса Set, 
можно просто сразу использовать Set методы

2022-06-22 15:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void addFriend(@PathVariable String id, @PathVariable String friendId) {
айдишники можно сразу сделать Integer или int типом, 
таким образом, потом не придется их кастить 

относится ко всем похожим местам

2022-06-22 15:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparing(film -> film.getAmountLikes().size(), Comparator.reverseOrder()))
для улучшения разделения ответственности, компаратор можно вынести в отдельный метод,
или если его не исользовать, то можно классом Film симплементировать интерфейс Comparable

2022-06-22 15:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return result;
отличный получился стрим,
но его можно не сохранять в перменную result, а просто сразу возвращать

2022-06-22 15:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            }
попробуй эту логику сделать через стрим, 
должно получится посимпотичней

2022-06-22 15:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
тип хэшсета films лучше сделать Map, так будет правильней с точки зрения полиморфизма

2022-06-24 09:55 UTC, madromk commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    }
Роман, так у нас же поля приватные. Я не могу напрямую обратится к переменной, даже если у неё есть свои Set методы. Или я может я неправильно твою мысль понял

2022-06-24 09:57 UTC, madromk commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            filmStorage.updateFilm(film);
Всё что ты написал, я сделал кроме эксепшена. Его нельзя перенести в сервис, потому что аннотация @ExceptionHandler работает только в контроллерах.

2022-06-26 19:36 UTC, Fleaman777 requested changes

2022-06-26 19:36 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
такую проверку лучше вынести в слой сервиса

2022-06-26 19:36 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        }
аналагично, логику с проверкой есть юзер или нет, лучше делать в сервисе

относится ко всем похожим местам в контроллере. 

по хоршему, контроллер должен отвечать только за полкчение реквестов и отправку респонсов, а всю остальную логику должны выполянять др. сервисы

2022-07-12 14:43 UTC, merged