ФЗ 11 спринта. Добавление баз данных
madromk/java-filmorate pull request #5
Opened 2022-07-20 10:13 UTC by madromk

2022-07-21 07:47 UTC, Fleaman777 requested changes

2022-07-21 07:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/genres/{id}")
эндпоинты для жанров и рейтингов можно перенести в отдельные контроллеры, 
так сказать, разделим ответсвенность

2022-07-21 07:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    //@ResponseBody
можно даже совсем удалить эту аннотацию, т.к. она содержится внутри аннотации @RestController

2022-07-21 07:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT name FROM genres WHERE category_id = ?";
в сторедже применим тот же подход, что и в контроллере, 

для жанров и рейтингов, лучше создать свои ДбСтореджи, что бы в будущем было проще расширять функционал и поддерживать старый код

2022-07-21 07:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                ", rate = ? WHERE film_id = ?";
хорошие составляешь запросы как по структуре, так и просто по написанию: 
ключевые слова например UPDATE, FROM и пр. в верхнем регистре, название таблиц и столбцов, в нижнем

2022-07-21 07:47 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/crud/CrudUserTest.java
> +}
тесты еще нужно дописать: 

согласно заданию,  все публичные методы хранилища  должны быть покрыты тестами.

т.е. должно быть как минимум 4 тест класса (на каждый сторедж), 
и в каждом классе различные тесты на публичные методы

2022-07-21 07:51 UTC, Fleaman777 requested changes

2022-07-21 07:51 UTC, Fleaman777 commented on README.md
> +![Схема базы данных приложения](filmorate_scheme_database.png)
отличная схема бд

2022-07-25 18:33 UTC, Fleaman777 requested changes

2022-07-25 18:33 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/mapRow/RowTo.java
> +public class RowTo {
если не быть в контексте приложения, то из названия не совсем понятно за что отвечает этот класс

2022-07-25 18:33 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/FilmDbStorageTest.java
> +        }
вот эта логика с if хороший кандидат, что бы вынести ее в метод с аннотацией @BeforeEach или @BeforeAll 

таким образом, нам не нужно будет писать ее в каждом тест методе

2022-07-25 18:33 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/FilmDbStorageTest.java
> +    public void addFilms() {
этот метод и addUsers вспомогательные методы для тестов, поэтому их можно сделать private и перенести в конец класса

2022-07-25 18:33 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/GenreDbStorageTest.java
> +        System.out.println(genreDbStorage.findAllGenres());
в тестах нужно именно проверять, что бы ожидаемый результат совпал с реальным при определенных условиях, 
иногда тесты бывают немного глупыми, как например в этом случае: проверить, что достается все то,  что было добавлено при создании таблицы, 
но в будущем такие тесты будут помогать рефакторить код и делать новые фичи без больших рисков, 
поэтому, здесь надо проверить, что все жанры отдаются нормально

2022-07-25 18:33 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/RatingMpaDbStorageTest.java
> +        System.out.println(ratingMpaDbStorage.findAllMpaRatings());
здесь аналагично с жанрами

2022-07-25 18:33 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/UserDbStorageTest.java
> +public class UserDbStorageTest {
в этом тесте применимы замечания из FilmDbStorageTest

2022-07-27 07:58 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/GenreDbStorageTest.java
> +        genres.add(genre6);
тест можно сделать чуть покомпактней, если жанры добавлять через конструктор 
List<Genre> genres = List.of(new Genre(id++,  комедия), new Genre(id++,  Драма))....

или прям совсем по хорошему, можно через sql скрипт для этого тест класса заполнить базу, 
а потом проверить, что все в ней на месте

2022-07-27 09:45 UTC, madromk commented on src/test/java/ru/yandex/practicum/filmorate/dbStorage/GenreDbStorageTest.java
> +        genres.add(genre6);
да, согласен. Не додумался об этом )

2022-08-26 11:30 UTC, merged